### ISSUE TITLE
Adding format 320... Error adding format 320: 'module' object has no attribute 'ParseFile'

### ISSUE THREAD

**Issue by JuezFenix** [Mechazawa/pthbetter-crawler#9]
Hi,

When the script do the job, on any transcode try, i get "Adding format 320... Error adding format 320: 'module' object has no attribute 'ParseFile'"
No torrent created or upload do it.
I try mktorrent from repo and from github. Same result.
What can happend?

**Comment by Ewan-S** [comment]
Same problem here. Any format, any upload. As you say, I think its a problem with mktorrent? Would up/down-grading work?

Here is the error:
Error adding format <format>: 'module' object has no attribute 'ParseFile'

**Comment by Mechazawa** [comment]
Odd, can you run the following and post the output?
```python
import mechanize
print mechanize.__version__, ', '.join(mechanize.__dict__.keys())
```

**Comment by rtpwilliams** [comment]
Hey there, I'm having the same problem. Here is my mechanize output.

`pizzahero@brisket ~/pthbetter-crawler $ python
Python 2.7.13 (default, Feb 28 2017, 03:23:26) 
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mechanize
>>> print mechanize.__version__, ', '.join(mechanize.__dict__.keys())
(0, 3, 1, None, None) HTTPRedirectDebugProcessor, HTTPResponseDebugProcessor, absolute_import, HTTPRedirectHandler, __path__, HTTPEquivProcessor, HiddenControl, IgnoreControl, _debug, _http, HTTPDefaultErrorHandler, FormNotFoundError, Browser, HTTPSClientCertMgr, urljoin, __file__, urlretrieve, OpenerDirector, Control, CheckboxControl, CacheFTPHandler, _html, HTTPDigestAuthHandler, TextareaControl, ImageControl, _urllib2_fork, _gzip, AmbiguityError, Label, _mechanize, AbstractBasicAuthHandler, _urllib2, DefaultCookiePolicy, __all__, LocateError, _clientcookie, RadioControl, urlopen, TextControl, Link, ScalarControl, HTTPSHandler, FTPHandler, _response, LinkNotFoundError, __builtins__, MozillaCookieJar, __name__, __version__, CookieJar, _version, BrowserStateError, ControlNotFoundError, LoadError, _useragent, CookiePolicy, _opener, install_opener, SubmitButtonControl, request_host, OpenerFactory, Cookie, HTTPRefreshProcessor, HTTPErrorProcessor, __doc__, HTTPPasswordMgrWithDefaultRealm, _form_controls, HTTPRobotRulesProcessor, HTTPHandler, _util, SubmitControl, logging, str2time, HTTPError, HTTPCookieProcessor, History, HTTPGzipProcessor, UserAgentBase, HTTPBasicAuthHandler, FileCookieJar, UnknownHandler, effective_request_host, RobotExclusionError, FileControl, ProxyBasicAuthHandler, HTTPRefererProcessor, build_opener, USE_BARE_EXCEPT, HTMLForm, _request, ProxyHandler, PasswordControl, BaseHandler, lwp_cookie_str, Factory, _form, _headersutil, ListControl, ItemNotFoundError, ContentTooShortError, SelectControl, XHTMLCompatibleHeadParser, Missing, FileHandler, HTTPPasswordMgr, __package__, UserAgent, LWPCookieJar, _sockettimeout, URLError, _rfc3986, ProxyDigestAuthHandler, seek_wrapped_response, _auth, AbstractDigestAuthHandler, Request, Item, SeekableResponseOpener, make_response, HTTPProxyPasswordMgr, response_seek_wrapper, ItemCountError`

**Comment by Trippler** [comment]
It looks like ParseFile has been removed in later versions of mechanize. Installing 0.2.5 fixes this issue.

**Comment by Mechazawa** [comment]
Thanks @Trippler!
